### ISSUE TITLE
Missing symbols in CT3-2019(KiCAD).sch which is provided in this repository.

### ISSUE THREAD

**Issue by snovotill** [locky-z/Curve-Tracer#2]
Hello locky_z. The schematic **CT3-2019(KiCAD).sch** which is provided in this repository cannot be fully displayed because some of the needed symbols are only available in a private library named **CT3** which does not come with KiCad. Please see the attached exported KiCad schematic to see how the following components cannot be displayed: **IDC-10 CK1**, **M62359 IC1**, **ADS7871 IC201**, **STC5608AD IC?**.

Therefore I would like to request that that one of the following files be uploaded to this repository alongside the schematic **CT3-2019(KiCAD).sch** which is already provided here, so that it will display properly.
(1) Either the **cache.lib** which Eschema creates every time you edit and save the schematic.
(2) Or the private **CT3 library** which KiCad creates every time the schematic is edited and saved.

Thank you for this amazing curve tracer which I purchased from you in October.
![MissingSymbols](https://user-images.githubusercontent.com/37263727/98494207-3aaa3400-21f1-11eb-999e-3d0cf58bb5cd.png)

**Comment by locky-z** [comment]
Have upload kiCAD project file included lib.
